### ISSUE TITLE
windows support 

### ISSUE THREAD

**Issue by amayra** [SirMetathyst/Syo#2]
how to use in windows ?

**Comment by SirMetathyst** [comment]
You'll need to first download "Syo.exe" from the releases page. To use it you can open up "Command Prompt" or powershell. You'll need to "cd" to the directory which contains Syo.exe then just run the command ".\syo.exe -l 1s -w 10 -o -n n7104eb" If you don't want to do it that way you create a file and paste "./syo.exe -l 1s -w 10 -o -n n7104eb" in there, save as batch script: "start_syo.bat" then run that. Remember to replace "n7104eb" with the id of the novel(s) you want to download. Btw, it can't download novels off the R18 subdomain of syosetu.
